### ISSUE TITLE
AssetsApiIT failure to search for DDO's

### ISSUE THREAD

**Issue by tmarble** [oceanprotocol/squid-java#80] opened 2019-03-18 18:55 UTC
## Expected Behavior

Integration tests pass (per the README).

## Current Behavior

One integration test fails:
```
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   AssetsApiIT.search:173 » DDO Unable to search for DDO's: 
[INFO] 
[ERROR] Tests run: 30, Failures: 0, Errors: 1, Skipped: 2
```

## Step to Reproduce the problem

Please provide detailed steps for reproducing the issue.

1. Remove filesystem side effects:
```
root@cerise:/# rm -rf /home/tmarble/.ocean/
```

2. Remove all docker images (WARNING: this will delete non-Ocean related containers)
```
docker rmi $(docker images -q)
```

3. Update to the latest barge:
```
commit 7f1b8d1df0581331e3a3b9655124fdde6f8967dc (HEAD -> develop, origin/develop, origin/HEAD)
```

4. Start barge:
```
KEEPER_VERSION=v0.8.5 bash start_ocean.sh --latest --no-pleuston --local-spree-node
```

5. Wait for a few minutes for Keeper to deploy contracts:
```
tmarble@cerise 268 :) ls -l ${HOME}/.ocean/keeper-contracts/artifacts/
total 180
-rw-r--r-- 1 tmarble users 10758 Mar 18 12:20 AccessSecretStoreCondition.spree.json
-rw-r--r-- 1 tmarble users 14861 Mar 18 12:20 AgreementStoreManager.spree.json
-rw-r--r-- 1 tmarble users 16141 Mar 18 12:20 ConditionStoreManager.spree.json
-rw-r--r-- 1 tmarble users  1652 Mar 18 12:20 DIDRegistryLibrary.spree.json
-rw-r--r-- 1 tmarble users 10255 Mar 18 12:20 DIDRegistry.spree.json
-rw-r--r-- 1 tmarble users  9913 Mar 18 12:20 Dispenser.spree.json
-rw-r--r-- 1 tmarble users  2996 Mar 18 12:20 EpochLibrary.spree.json
-rw-r--r-- 1 tmarble users 13714 Mar 18 12:20 EscrowAccessSecretStoreTemplate.spree.json
-rw-r--r-- 1 tmarble users 13365 Mar 18 12:20 EscrowReward.spree.json
-rw-r--r-- 1 tmarble users 11407 Mar 18 12:20 HashLockCondition.spree.json
-rw-r--r-- 1 tmarble users 10256 Mar 18 12:20 LockRewardCondition.spree.json
-rw-r--r-- 1 tmarble users 21290 Mar 18 12:20 OceanToken.spree.json
-rw-r--r-- 1 tmarble users     0 Mar 18 12:20 ready
-rw-r--r-- 1 tmarble users  9890 Mar 18 12:20 SignCondition.spree.json
-rw-r--r-- 1 tmarble users  9692 Mar 18 12:20 TemplateStoreManager.spree.json
tmarble@cerise 269 :)
```

6. Update to the latest squid-java
```
commit d44a0c0d221ce1025302e33f12f1cdf8ff8b7e2e (HEAD -> develop, origin/develop, origin/HEAD)
```

7. Update the configuration:
```
tmarble@cerise 275 :) ./src/test/resources/scripts/updateConfAddresses.sh 
Setting up SignCondition address to 0xEEE56e2a630DD29F9A628d618E58bb173911F393
Setting up HashLockCondition address to 0x85cCa2B01adddCA8Df221e6027EE0D7716224202
Setting up LockRewardCondition address to 0x3a3926f3f88F1eE05164404f93FDb3887cbE8e35
Setting up AccessSecretStoreCondition address to 0x19513460bc16254c74AE806683E906478A42B543
Setting up EscrowReward address to 0x8F006DbB3727d18f032C5618595ecDD2EDE13b61
Setting up EscrowAccessSecretStoreTemplate address to 0xD306b5edCDC7819E1EB80B43De6548931706A3f4
Setting up OceanToken address to 0x726baA2f854A3BEC2378a707AeB38c9d933Ebad6
Setting up Dispenser address to 0xF152cF3c67dFD41a317eAe8fAc0e1e8E98724A13
Setting up DIDRegistry address to 0xc354ba9AD5dF1023C2640b14A09E61a500F21546
Setting up ConditionStoreManager address to 0x336EFb3c9E56F713dFdA4CDB3Dd0882F3226b6eE
Setting up TemplateStoreManager address to 0xfeA10BBb093d7fcb1EDf575Aa7e28d37b9DcFcE9
Setting up AgreementStoreManager address to 0x645439117eB378a6d35148452E287a038666Ed67
tmarble@cerise 276 :)
```

8. Run integration tests per the README
```
mvn clean verify -P integration-test -B -V > integration-test-0318-bis.log 2>&1 &
```

### Possible Solution

?

## Specifications

* Version: `d44a0c0d221ce1025302e33f12f1cdf8ff8b7e2e`
* Java: `openjdk version "1.8.0_191"`
* Barge: `7f1b8d1df0581331e3a3b9655124fdde6f8967dc`
* OS:  `Linux cerise 4.16.0-2-amd64 #1 SMP Debian 4.16.16-2 (2018-06-22) x86_64 GNU/Linux`

## Failure Logs

```
[ERROR] Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 170.696 s <<< FAILURE! - in com.oceanprotocol.squid.api.AssetsApiIT
[ERROR] search(com.oceanprotocol.squid.api.AssetsApiIT)  Time elapsed: 15.175 s  <<< ERROR!
com.oceanprotocol.squid.exceptions.DDOException: Unable to search for DDO's: 
	at com.oceanprotocol.squid.api.AssetsApiIT.search(AssetsApiIT.java:173)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: 
Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: java.io.StringReader@1af3bf5b; line: 1, column: 1002] (through reference chain: java.util.ArrayList[0]->com.oceanprotocol.squid.models.DDO["authentication"]->java.util.ArrayList[0]->com.oceanprotocol.squid.models.DDO$Authentication["publicKey"])
	at com.oceanprotocol.squid.api.AssetsApiIT.search(AssetsApiIT.java:173)
```

**Comment by aaitor** [comment] 2019-03-19 17:34
Unable to reproduce in local using the same setup. That commit works in Travis in a clean environment: https://travis-ci.com/oceanprotocol/squid-java/builds/104716972

**Comment by aaitor** [comment] 2019-04-02 10:55
Unable to reproduce and without additional feedback. Closing this one, if the bug is found again, please reopen or open a new one.

**Closed by aaitor** 2019-04-02 10:55 UTC
